### ISSUE TITLE
Add linting options to catch reactivity issues

### ISSUE THREAD

**Issue by 100terres** [solidjs/solid-docs#147]
**Problem**

As the reactivity might be difficult to understand for beginner users, it might also be difficult for them to catch reactivity issues in their own codebase without any help. _(That might also be true for regular users.)_

Having a linter running in the editor would help our users to catch errors with their code. I've searched in both documentation repos and I couldn't find the mention that a linter would help them.

**Proposed solution**

I haven't tested it personally yet, but maybe mentioning this [eslint plugin](https://github.com/joshwilsonvu/eslint-plugin-solid) in the documentation could help reduce some frictions for people trying out solid or more regular users. _Maybe the SolidJS organization should consider implementing its own eslint plugin. The errors catch by the linter could include a reference to the solid documentation. Owning the linter plugin would make it easier to update the documentation at the same time as the linter._

Mentioning the linting options could be part of a _Setup your editor [Tutorial]_ and/or in the [Solid Code Conventions [How-To Guide]](https://github.com/solidjs/solid-docs-next/issues/49). Those pages could be referenced in other places in the documentation where we explain how the core primitives work and/or how to use them.

**External examples**

Here's how the react documentation mentions their linter plugin to help users catch errors in their code:

- https://beta.reactjs.org/learn/lifecycle-of-reactive-effects#what-to-do-when-you-dont-want-to-re-synchronize
- https://beta.reactjs.org/learn/editor-setup#linting
- https://reactjs.org/docs/hooks-rules.html#eslint-plugin

As it's mentioned in the react documentation

> The linter is your friend

Let me know what you think.

**Comment by 100terres** [comment]
On a personal note. The first time I tried solid, I've wasted a couple of hours of my time, because I broke the reactivity. I had destructured the props of one of my components. Coming from react where we often destructed the props, so it was hard to track down the issue without any help. This could have been caught right away by a linter and save me a lot of time.

**Comment by joshwilsonvu** [comment]
I think you'll be pleased to know that we're in the process of moving `eslint-plugin-solid` into the [Community](https://github.com/solidjs-community) organization and integrating it into [the playground](https://playground.solidjs.com). We fully intend to keep the linter in sync with the documentation, and mentioning it in the "Installing Solid" section sounds like a good idea to me.

**Comment by 100terres** [comment]
@joshwilsonvu That's a good news! :slightly_smiling_face:

**Comment by michaelessiet** [comment]
Thank you for bringing this issue. This issue has been addressed in our latest merge #152. Check it out [here](https://docs.solidjs.com/guides/how-to-guides/get-ready-for-solid/linting)

**Comment by michaelessiet** [comment]
Closing this as I have added a section addressing this in the docs. And I will be adding references to linter benefits here and there within the docs from now on
