### ISSUE TITLE
Accessibility Guide [How-To Guide]

### ISSUE THREAD

**Issue by Jutanium** [solidjs/solid-docs#51]
This will cover best practices for creating accessible UIs with Solid. Can include [`solid-aria`](https://github.com/solidjs-community/solid-aria). More research required.

**Comment by crutchcorn** [comment]
# Rough Outline

This is my thoughts on what a rough outline of this content could look like

- WCAG/Intro to A11Y
- Semantic HTML
- Aria
- Element association
    - Implicit element attribution (label<->input)
    - Explicit element attribution
        - Unique ID Generation/handling
- Tab focusing 
    - Outline styles
    - TabIndex handling
    - `ref` usage with `focus()`
- Live announcement
- JSX A11Y ESlint
- Mouse events
    - Use CSS!, not JS (for hover states, focus states)
- Testing methodologies
    - Manual testing disclaimer
    - Automated role/user-based testing (w/ `solid-testing-library`), link out to docs
- External resources
    - Official WCAG guidelines
    - Unofficial resources

**Comment by robertvanhoesel** [comment]
Not sure how exhaustive you want this guide to be, but some suggestions for other best practices/pointers on how to make apps more accessible:
- Keyboard navigation and shortcuts (i.e. with https://github.com/solidjs-community/solid-primitives/tree/main/packages/keyboard#createShortcut )
- Resetting focus to start of the page after routing (especially required with nested routing)
- Respecting reduce-motion and prefers-contrast

While I don't have a whole lot of experience implementing WCAG in a Solid app, I'm definitely open to help writing out this guide a bit further.
