### ISSUE TITLE
Log 404s so we can redirect pages getting hits

### ISSUE THREAD

**Issue by titoBouzout** [solidjs/solid-docs#526]
Issue filled as a reminder to log 404s in case we can redirect to new content.

**Comment by LadyBluenotes** [comment]
@atilafassina @titoBouzout @danieljcafonso What's the status on this issue? Has it been addressed at all or does it still need to be?

**Comment by LadyBluenotes** [comment]
I believe this has been addressed now so I'm closing this 😎
