### ISSUE TITLE
Side panel clipping

### ISSUE THREAD

**Issue by slvtnskx** [solidjs/solid-docs#565]
### 📝 Issue Description

The side panel gets clipped off in some screen sizes and aspect ratios.

### 📋 On which page(s) it occurs

The issue occurs on all pages of the documentation.

### 🤔 Expected Behavior

It works fine in some screen aspect ratios:
![image](https://github.com/solidjs/solid-docs-next/assets/42350728/e184a792-b902-48a4-982b-645616461f31)

### 👀 Current Behavior

But not in 1280x880px for example
![image](https://github.com/solidjs/solid-docs-next/assets/42350728/e2dd2a94-9ff2-485f-90b0-3449138b9500)

### 🖥️ Browser

Chrome Version 109.0.5414.120 (Official Build) (64-bit)

**Comment by LadyBluenotes** [comment]
closed with #644
