### ISSUE TITLE
[Content]: The Stores page seems to have incorrect table of content

### ISSUE THREAD

**Issue by ngdangtu-vn** [solidjs/solid-docs#686]
### 📚 Subject area/topic

[concepts/stores.mdx](https://github.com/solidjs/solid-docs-next/blob/e2127a35fbe94a520c6790411f3ec103b71d7724/src/routes/concepts/stores.mdx)

### 📋 Page(s) affected (or suggested, for new content)

https://docs.solidjs.com/concepts/stores

### 📋 Description of content that is out-of-date or incorrect

I believe the section [`Extracting raw data with unwrap`](https://docs.solidjs.com/concepts/stores#extracting-raw-data-with-unwrap) should be a child of [`Store utilities`](https://docs.solidjs.com/concepts/stores#store-utilities) section since `unwrap` is a utility function of Store.

**Comment by LadyBluenotes** [comment]
Thank you for flagging this!

**Comment by LadyBluenotes** [comment]
Closed with #707
