### ISSUE TITLE
[Content]: Typo in "onCleanUp". On the docs are written "onCleanUp", but the correct in implementation is "onCleanup"

### ISSUE THREAD

**Issue by dhanielsales** [solidjs/solid-docs#689]
### 📚 Subject area/topic

/index.mdx

### 📋 Page(s) affected (or suggested, for new content)

https://docs.solidjs.com/guides/fetching-data#refetch

### 📋 Description of content that is out-of-date or incorrect

In refresh section, the example show an typo in "onCleanUp" but the correct in implementation and import is "onCleanup"

Just a simple fix to correct to "onCleanup" will works well.

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

On Docs

![Captura de tela de 2024-04-19 11-16-39](https://github.com/solidjs/solid-docs-next/assets/40248790/931c0a40-9cc7-4ff9-8b76-b77a7d541935)

On Test

![Captura de tela de 2024-04-19 11-16-11](https://github.com/solidjs/solid-docs-next/assets/40248790/06430246-b16f-4776-97a5-e5f543e09019)

**Comment by LadyBluenotes** [comment]
Fixed with #708
