### ISSUE TITLE
[Content]: Escaping routes

### ISSUE THREAD

**Issue by ematipico** [solidjs/solid-docs#733]
Hi,

I read the explanation of the escaped routes, and I find it difficult to understand what they do.

Specially, it talks about different layouts, then it proceeds to show a snippet with an escaped route, but then **it doesn't explain** the actual effects on the browser URLs, and what the new added files do.

**Comment by LadyBluenotes** [comment]
Related to #841 - closing because duplicate.

**Comment by ematipico** [comment]
My issue was opened before and was marked as a duplicate 🤷‍♂️  Well, I'm glad it got some visibility, at least

**Comment by LadyBluenotes** [comment]
@ematipico Just because the other one has a bit more in the description :) gives us a better understanding of what's needed
