### ISSUE TITLE
[Content]: Incorrect explanation of `isSVG` on <Portal>

### ISSUE THREAD

**Issue by jer3m01** [solidjs/solid-docs#767]
### 📚 Subject area/topic

Reference

### 📋 Page(s) affected (or suggested, for new content)

https://docs.solidjs.com/reference/components/portal

### 📋 Description of content that is out-of-date or incorrect

> [...] and `isSVG` is required if inserting into an SVG element so that the `<div>` is not inserted.

Should be replaced by something like 
> so that a `<g>` is inserted instead of a `<div>`.

Source: https://github.com/solidjs/solid/blob/b5a379f889e8f7a208bc223b908a0fdcf353d944/packages/solid/web/src/index.ts#L87C27-L87C81

**Comment by LadyBluenotes** [comment]
Looks like this was addressed! Ty for creating the issue
