### ISSUE TITLE
[Request]: Improve lighthouse score/ reduce bundle size

### ISSUE THREAD

**Issue by CasperSond** [solidjs/solid-docs#772]
### What is this request related to?

Request

### 📋 Suggested

https://docs.solidjs.com/
https://pagespeed.web.dev/analysis/https-docs-solidjs-com/q2ourx04r6?form_factor=mobile

### 📋 General description or bullet points

As someone new to Solid and SolidStart, I understand the importance of performance. However, I was surprised to see that the Lighthouse score on docs.solidjs.com only reached 70 for performance, as measured by pagespeed.web.dev. The primary issue seems to be a total blocking time of over 5000 ms, caused by the large JavaScript asset client-BVBETh-o.js.

I'm unsure why the website requires such a large JavaScript file for its advanced features. Since the SolidStart documentation should exemplify speed and excellent performance metrics, it would be beneficial to optimize the bundle size. For comparison, SvelteKit (https://kit.svelte.dev/) has a largest JavaScript asset of only 23 KB (gzipped), whereas client-BVBETh-o.js is 457 KB (gzipped).

**Comment by davedbase** [comment]
Thanks for reporting the issue. The docs project has focused mostly on content and will continue to do so before there are plans to optimize the payload.

We appreciate the report though.

**Comment by brenelz** [comment]
I think this can probably be closed. We merge a PR that hopefully improves this. I think the main culprit was the syntax highlighting on the client

**Comment by LadyBluenotes** [comment]
@brenelz thanks for the flag.

@CasperSond if you think the current fix is insufficient, please open another issue!
