### ISSUE TITLE
Dynamic imports should have `lazy()` on Router example snippets

### ISSUE THREAD

**Issue by hugomcm** [solidjs/solid-docs#775]
### 📚 Subject area/topic

/solid-router/getting-started/config.mdx

### 📋 Page(s) affected (or suggested, for new content)

/solid-router/getting-started/config.mdx

### 📋 Description of content that is out-of-date or incorrect

Hello there,

I'm using:
solid-js@1.8.17;
@solidjs/router@0.13.5

The following example isn't working, at least for me. I always get a "dev.js:623 Uncaught TypeError: Comp is not a function" 
```js
import { render } from "solid-js/web";
import { Router } from "@solidjs/router";

const routes = [
    {
    path: "/",
    component: import("/routes/index.js"),
  },
    {
        path: "/hello-world",
        component: <h1>Hello, World!</h1>
    },
    {
        path: "/about",
        component: import("/routes/about.js"),
    }
]

render(() => <Router>{routes}</Router>, document.getElementById("app"));
```

This only works if the JSX is wrapped in a unary function. In the case of a dynamic import, it needs the lazy wrap and the unary function wrap also.
Like this:
```js
import { render } from "solid-js/web";
import { lazy } from "solid-js";
import { Router } from "@solidjs/router";

const routes = [
    {
        path: "/",
        component: () => lazy(() => import("/routes/index.js")),
    },
    {
        path: "/hello-world",
        component: () =><h1>Hello, World!</h1>
    },
    {
        path: "/about",
        component: () => lazy(() => import("/routes/about.js")),
    }
]

render(() => <Router>{routes}</Router>, document.getElementById("app"));
```

**Comment by atilafassina** [comment]
Hey, @hugomcm .
I believe you're right!
I set the issue to planned so we can address that ASAP.
