### ISSUE TITLE
[Content]: Dynamic webcomponent props are lowercased unless explicity `prop:`'d

### ISSUE THREAD

**Issue by chee** [solidjs/solid-docs#783]
### 📚 Subject area/topic

<Dynamic/>

### 📋 Page(s) affected (or suggested, for new content)

- https://docs.solidjs.com/concepts/control-flow/dynamic

### 📋 Description of content that is out-of-date or incorrect

It might be helpful to note here that a prop passed to <Dynamic/> will have its name lower-cased if the `component` is a web component string name! (or elided completely if it is a string without a `-` in it!)

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

https://playground.solidjs.com/anonymous/1bce5e3c-dec2-42e9-939a-b22a6a916b19

**Comment by titoBouzout** [comment]
Thanks @chee for filling the issue! I think this is unintentional. Details and possible fix here https://github.com/ryansolid/dom-expressions/pull/351 feel free to participate! I will close this one for now, we can discuss it on the linked pr.
