### ISSUE TITLE
Spelling error and unclear sentence in docs

### ISSUE THREAD

**Issue by quentinkrammer** [solidjs/solid-docs#805]
### 📚 Subject area/topic

/solid-start/building-your-application/static-assets.mdx

### 📋 Page(s) affected (or suggested, for new content)

https://docs.solidjs.com/solid-start/building-your-application/static-assets#public-directory-versus-imports

### 📋 Description of content that is out-of-date or incorrect

> If you want the links to your assets to update when they changes, the public directory is the best choice. This gives you full control over the url path to your assets and ensures that the links to your assets never change.

- The "s" in "changes" should not be there.
- The way the first sentence is structured it is ambiguous whether "they" refers to "links" or to "assets". (I guess you mean "assets" but in general I have a hard time understanding this, so not sure)
- I also find the first sentence hard to make sense of. As far as I understand, asset links are totally stable when using the public directory. So why would links be updating.  Isn't the whole point that links do NOT update when using the public directory?

Sry perhaps, I am just not understanding this.

**Comment by LadyBluenotes** [comment]
Closing this because we don't currently have AI in our search - but thank you for the flag!
