### ISSUE TITLE
[Content]: AI search

### ISSUE THREAD

**Issue by Vahe-1810** [solidjs/solid-docs#807]
### 📚 Subject area/topic

/concepts/intro-to-reactivity.mdx

### 📋 Page(s) affected (or suggested, for new content)

https://docs.solidjs.com/concepts/intro-to-reactivity

### 📋 Description of content that is out-of-date or incorrect

when i tried to ask a question i got this error
![image](https://github.com/solidjs/solid-docs-next/assets/116266266/ceea458c-70c8-4e78-a8ac-8e4c2baaed8d)

**Comment by LadyBluenotes** [comment]
Closing this because we don't have AI in our search right now - thank you for the flag though!
