### ISSUE TITLE
[Content]:an issue with the lazy-loading section of solid-router

### ISSUE THREAD

**Issue by namejiahui** [solidjs/solid-docs#817]
### 📚 Subject area/topic

/solid-router/advanced-concepts/lazy-loading.mdx

### 📋 Page(s) affected (or suggested, for new content)

https://docs.solidjs.com/solid-router/advanced-concepts/lazy-loading

### 📋 Description of content that is out-of-date or incorrect

![image](https://github.com/user-attachments/assets/1d5fb7d5-359c-4316-b2d4-3d0b886dd745)

**Comment by LadyBluenotes** [comment]
Fixed with #827
