### ISSUE TITLE
[Request]: When to use useNavigate vs redirect

### ISSUE THREAD

**Issue by klequis** [solidjs/solid-docs#820]
### What is this request related to?

Request

### 📋 Suggested

- https://docs.solidjs.com/solid-router/reference/data-apis/response-helpers#redirect

And maybe in here as well: https://docs.solidjs.com/solid-router/reference/primitives/use-navigate

### 📋 General description or bullet points

Solid router has `useNavigate` and `redirect`. It wasn't clear to my why. I asked in Discord

@klequis
```
└── 📁categories
    └── [...notfound].jsx
    └── keyboards.jsx
    └── mice.jsx
```

I want `[...notfund].jsx` to redirect/navigate to `/products/index.jsx`. Does it matter if I use `redirect` vs `useNavigate`? 

And got an answer from Ryan I would not have thought of:

"redirect actually only works inside cache and action functions (edited)
everywhere else useNavigate"

This seems like a good add to the doc.

**Comment by brenelz** [comment]
We could probably add a note to the redirect page that it only works in cache/action functions. Thoughts?
