### ISSUE TITLE
[Content]: Catch-all parameter returns entire path not just the invalid part.

### ISSUE THREAD

**Issue by klequis** [solidjs/solid-docs#837]
### 📚 Subject area/topic

SolidStart > Routing

### 📋 Page(s) affected (or suggested, for new content)

https://docs.solidjs.com/solid-start/building-your-application/routing#catch-all-routes

### 📋 Description of content that is out-of-date or incorrect

Doc says, "A catch-all route will have one parameter which is a forward-slash delimited string of all the URL segments **after the last valid segment**."

This is not correct. When a route is invalid the catch-all route's parameter contains the entire URL path, both valid and invalid segments.

It's crunch time for me, but I will follow-up with a PR unless the issue is closed.

**Comment by brenelz** [comment]
@ryansolid not sure if this is a documentation problem or a router problem.

> For example, with the route [...post] and a URL path of /post/foo the params object returned from the useParams primitive will have a post property with the value of foo

In my tests I get 

```
{ "post": "post/foo" }
```

**Comment by ryansolid** [comment]
I think what you get is correct.

Like what would the invalid part be? It matches or it doesn't. If the catch all was under a post folder.. ie `/post/[,,,post]` then I'd expect only `foo`. But then `/baz/[...post]` wouldn't match. A path of only `[,,,post]` would always return the full path.
