### ISSUE TITLE
[Content]: Store update path syntax - range of array indices is unclear

### ISSUE THREAD

**Issue by ak37165** [solidjs/solid-docs#838]
### 📚 Subject area/topic

concepts/stores

### 📋 Page(s) affected (or suggested, for new content)

https://docs.solidjs.com/concepts/stores#range-specification

### 📋 Description of content that is out-of-date or incorrect

The range specification first paragraph says you can specify a range of indices. So to cover all indices, I would think one would use
`[0, array.length-1]`

However, the example for array directly as the store uses `to: store.length` - should that be `store.length-1` instead of store.length?

**Comment by brenelz** [comment]
Yeah I think it should be store.length -1
