### ISSUE TITLE
[Other]: Local fork not working

### ISSUE THREAD

**Issue by femincan** [solidjs/solid-docs#862]
I forked the project and cloned it. I installed all the dependencies but the project is not working (The dev mode starts but when I enter the website it gives errors and stops working.). It shows errors because of environment variables required by Orama search functionality.

The environment variables are:

- `VITE_ORAMA_ENDPOINT`,
- `VITE_ORAMA_API_KEY`,
- `VITE_ORAMA_SECURE_PROXY`.

I can't find any solution in `CONTRIBUTING.md`.

I workaround the problem by setting the required three variables with some placeholder value because the values should not be `undefined`. Currently, the project runs with some errors.

Could there be a point I missed?

**Comment by namejiahui** [comment]
Indeed, I don’t see the point of hiding these variables, as they can be found in this request.

![image](https://github.com/user-attachments/assets/369f0f2d-7146-49b5-949d-cc3e974ef4ea)

**Comment by titoBouzout** [comment]
Thanks for the report, this should be fixed now!
