### ISSUE TITLE
[Content]: Improve documentation on environment variables with SolidStart

### ISSUE THREAD

**Issue by LadyBluenotes** [solidjs/solid-docs#867]
### 📚 Subject area/topic

SolidStart / Env Variables

### 📋 Page(s) affected (or suggested, for new content)

https://docs.solidjs.com/configuration/environment-variables#environment-variables

### 📋 Description of content that is out-of-date or incorrect

Related links: 
- https://discord.com/channels/722131463138705510/861229287868858379/1281313867892396032
- https://discord.com/channels/722131463138705510/1281295496844939398/1281295496844939398

**Comment by atilafassina** [comment]
closed by #880
