### ISSUE TITLE
[Content]: Routes don't need to be in the /routes directory

### ISSUE THREAD

**Issue by klequis** [solidjs/solid-docs#870]
### 📚 Subject area/topic

/solid-start/building-your-application/routing.mdx

### 📋 Page(s) affected (or suggested, for new content)

https://docs.solidjs.com/solid-start/building-your-application/routing

### 📋 Description of content that is out-of-date or incorrect

Today I accidentally place a new route in `/src` instead of `/src/routes` and the route works. The doc states:

"Each file in the routes directory is treated as a route. To create a new route or page in your application, simply create a new file in the routes directory. "

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

I'll provide an example once I get an issue number.

**Comment by klequis** [comment]
Example

https://github.com/klequis/solid-docs-next-issue-870

Navigate to the `/products` route.

**Comment by atilafassina** [comment]
> Example
> 
> https://github.com/klequis/solid-docs-next-issue-870
> 
> Navigate to the `/products` route.

looks to me it's rendering the right file (`[...notfound].jsx`)
Am I missing something?

You can chance that in `app.config.ts` > `routesDir`.  I think that's the part which is missing in the docs.

<img width="711" alt="Screenshot 2024-09-21 at 23 00 58" src="https://github.com/user-attachments/assets/6d7c33d9-2687-4c3a-b424-9856dfed8d33">

**Comment by klequis** [comment]
Nope. It's me who is missing something. I saw route: /products and thought it went to products. Perhaps my UI design is poor :)
