### ISSUE TITLE
[Content]:Does useLocation return a signal or some other reactive data structure?

### ISSUE THREAD

**Issue by klequis** [solidjs/solid-docs#881]
### 📚 Subject area/topic

Router, useLocation

### 📋 Page(s) affected (or suggested, for new content)

https://docs.solidjs.com/solid-router/reference/primitives/use-location#uselocation

### 📋 Description of content that is out-of-date or incorrect

Someone in #general today made the assumption that `useLocation` returned a signal. I implicitly mad the same assumption. However, the doc says

"Retrieves reactive location object useful for getting things like pathname"

One could assume that a "reactive location object" is or is not a signal. I think if it is a signal it should say so. If not a signal then, at least to me, it implies that Solid has a reactive object/data structure that I have not see documented anywhere else.

**Comment by brenelz** [comment]
I personally don't see a problem with the wording of "Retrieves reactive location object". This would imply to me that its not a signal and just an object that changes based on the router location. Also I think the types help show its not a function call

Do you have suggestion how to make it more clear?

**Comment by LadyBluenotes** [comment]
I agree with @brenelz - if you have any suggestions on how to reword, please let us know but for now I'm going to close this issue.
