### ISSUE TITLE
[Content]: Improve docs on `untrack`

### ISSUE THREAD

**Issue by atilafassina** [solidjs/solid-docs#888]
### 📚 Subject area/topic

Solid core
[untrack](https://docs.solidjs.com/reference/reactive-utilities/untrack)

### 📋 Description of content that is out-of-date or incorrect

This page has only the type and a one-liner about what the method does.
Let's add an example use-case and a more thorough explanation.

**Comment by brenelz** [comment]
The link in the ticket didn't work for me. Should be the following:
https://docs.solidjs.com/reference/reactive-utilities/untrack

I don't feel I know enough about untrack to write about it. @devagrawal09 might be a good candidate

**Comment by atilafassina** [comment]
> The link in the ticket didn't work for me. Should be the following: https://docs.solidjs.com/reference/reactive-utilities/untrack
> 
> I don't feel I know enough about untrack to write about it. @devagrawal09 might be a good candidate

thanks! It was late and forgot to add the `docs.` subdomain on the link 🤦
