### ISSUE TITLE
[Bug]: Uncaught client exception with JIT disabled

### ISSUE THREAD

**Issue by kaathewisegit** [solidjs/solid-docs#938]
### 📝 Issue Description

The docs website doesn't work on Android Chromium with JIT disabled

### 📋 On which page(s) it occurs

All of them

### 🤔 Expected Behavior

The website working correctly.

### 👀 Current Behavior

The page loads correctly (I can see a flash of the rendered document), before throwing an exception almost immediately.

![image](https://github.com/user-attachments/assets/bc6c61e2-815c-4af6-a3ac-264d5c2adf04)

### 🖥️ Browser

[Vanadium](https://grapheneos.org/usage#web-browsing) 130.0.6723.73

### 📄 Additional Information

Vanadium is a hardened Chromium fork, so it should be more or less the same as Chromium on Android with JIT disabled by default.  When I enable JIT, the website works correctly.

**Comment by c727** [comment]
Same for cromite browser: https://github.com/uazo/cromite/
`ReferenceError: WebAssembly is not defined`

**Comment by c727** [comment]
seems to be fixed now 👍

**Comment by kaathewisegit** [comment]
Yep, works for me too
