### ISSUE TITLE
[Bug]: Install template command missing `"type":"module"` in `package.json`

### ISSUE THREAD

**Issue by panchi64** [solidjs/solid-docs#944]
### 📝 Issue Description

When running the Typescript template installation scripts with Bun the `package.json` that gets generated is missing the `"type": "module"` attribute. Causing vite to fail when trying to run the `bun dev` command with the following error:

```bash
bun dev    
$ vite
failed to load config from /home/REDACTED/front-end/vite.config.ts
error when starting dev server:
TypeError: require() async module "/home/REDACTED/front-end/vite.config.ts" is unsupported. use "await import()" instead.
    at <anonymous> (/home/REDACTED/front-end/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:66709:17)
    at processTicksAndRejections (native:7:39)
```

### 📋 On which page(s) it occurs

https://docs.solidjs.com/quick-start

### 🤔 Expected Behavior

A correctly generated `package.json` that does not cause any errors when attempting to launch the development server.

### 👀 Current Behavior

A `package.json` is generated with a missing `"type":"module"` attribute, causing vite to fail when launching the development server.

### 🖥️ Browser

Firefox 132.0 (64-bit)

**Comment by c727** [comment]
Got fixed by https://github.com/solidjs/templates/pull/153

**Comment by LadyBluenotes** [comment]
Closed https://github.com/solidjs/templates/pull/153

Thank you for pointing that out @c727
