### ISSUE TITLE
Occurrences of `load` instead of`preload`  to `router`

### ISSUE THREAD

**Issue by atilafassina** [solidjs/solid-docs#963]
### 📚 Subject area/topic

Solid-Router, data-fetching, preloading

### 📋 Page(s) affected (or suggested, for new content)

TBD

### 📋 Description of content that is out-of-date or incorrect

It's been reported that some code snippets haven't been adapted to change of name.

Previously to preload date in a route, one would write:

```ts
export const route = {
  load: () => {...}
}
```

But recently the `load` key has been renamed to `preload`

**Comment by tentaShiratori** [comment]
Thanks for the details! I'll start working on this issue. (By the way, I was using the name 白鳥 on Discord.)
