### ISSUE TITLE
[Content]: The example that explains why not to destruct props is not actually destructing

### ISSUE THREAD

**Issue by HakS** [solidjs/solid-docs#980]
### 📚 Subject area/topic

/concepts/components/props.mdx

### 📋 Page(s) affected (or suggested, for new content)

https://docs.solidjs.com/concepts/components/props#destructuring-props

### 📋 Description of content that is out-of-date or incorrect

The example says `const name = props.name;`, a correct example would be `const { name } = props` or destructing directly from the function
```js
function MyComponent({ name }) { // ❌: breaks reactivity and will not update when the prop value changes
  ...
}

function MyComponent(props) {
  const { name } = props; // ❌: breaks reactivity and will not update when the prop value changes
  const name = props.name; // ✓: by wrapping `props.name` into a function, `name()` always retrieves its current value
  const name = () => props.name; // ✓: by wrapping `props.name` into a function, `name()` always retrieves its current value
}
```

**Comment by edemaine** [comment]
`const name = props.name` does break reactivity, but I agree that it's not technically destructuring. I guess we can show both.
